name: birthdays
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  carousel_slider: ^4.1.1
  contacts_service: ^0.6.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  intl: ^0.17.0
  permission_handler: ^9.2.0
  rxdart: ^0.27.3
  shared_preferences: ^2.0.15
  snapping_page_scroll: ^2.1.0
  table_calendar: ^3.0.6
  timeago: ^3.2.2


dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^1.0.0
  flutter_local_notifications: ^9.4.1
  flutter_native_timezone: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  static_analyze_av: ^0.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/svg/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Rubik-Regular
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
